# Generated by Django 4.1.5 on 2023-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsefile', '0002_store_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='saldo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
